# Default configuration for options trading model training

data:
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  seq_length: 30

model:
  hidden_size: 768
  num_layers: 6
  num_heads: 8
  dropout: 0.1

training:
  batch_size: 32
  learning_rate: 1.0e-4
  num_epochs: 100
  device: "cuda"
  checkpoint_dir: "checkpoints"
  log_dir: "logs"

early_stopping:
  patience: 5
  min_delta: 1.0e-4

monitoring:
  use_wandb: false
  project_name: "options-oracle" 