# Default configuration for options trading model training

# Data configuration
data:
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  seq_length: 30

# Model configuration
model:
  hidden_size: 768
  num_layers: 6
  num_heads: 8
  dropout: 0.1

# Training configuration
training:
  batch_size: 32
  learning_rate: 1.0e-4
  num_epochs: 100
  device: "cuda"
  checkpoint_dir: "checkpoints"
  log_dir: "logs"

# Early stopping configuration
early_stopping:
  patience: 5
  min_delta: 1.0e-4

# Monitoring configuration
monitoring:
  use_wandb: false
  project_name: "options-oracle" 